runtime: python310

instance_class: F1

entrypoint: streamlit run app.py --server.port $PORT

env_variables:
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_SERVER_ENABLE_CORS: "false"
  STREAMLIT_SERVER_PORT: $PORT

automatic_scaling:
  min_instances: 1
  max_instances: 2
